In [1]:
from pyspark import SparkContext
from pyspark.sql.functions import countDistinct
sc=SparkContext()

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).


22/12/13 15:43:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/12/13 15:43:14 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.


In [2]:
import numpy as np


Pseude Code:

agrupar por user, device, gt
    para x, y, z sacar
        median
        desv
        max
        min

join data from different datasets into RDDs
Analize RDDs

Don´t repeat code!
avoid many (unnecessary) lines of code / repetitions

In [3]:
#columns = ["index", "arrival_time", "creation_time", "x", "y", "z", "user", "model", "device", "activity"]

pa = sc.textFile('Phones_accelerometer.csv')

pg = sc.textFile('Phones_gyroscope.csv')

wa = sc.textFile('Watch_accelerometer.csv')

wg = sc.textFile('Watch_gyroscope.csv')


In [19]:
split = wg.map(lambda x : x.split(","))
keyed = split.map(lambda x : (x[6] + "," + x[7]+ "," + x[9], np.array([1, float(x[3]), float(x[4]), float(x[5]), float(x[3])**2, float(x[4])**2, float(x[5])**2])))

sum = keyed.reduceByKey(lambda x, y : x + y)
std = sum.map(lambda x : (x[0], np.array([np.sqrt((x[1][4]/x[1][0])-(x[1][1]/x[1][0])**2), np.sqrt((x[1][5]/x[1][0])-(x[1][2]/x[1][0])**2), np.sqrt((x[1][6]/x[1][0])-(x[1][3]/x[1][0])**2)])))
mean = sum.map(lambda x : (x[0], np.array((x[1][1]/x[1][0], x[1][2]/x[1][0], x[1][3]/x[1][0]))))

#sum_std = keyed.map(lambda x: (x[1][1]  - mean[1][1])**2)
'''std = sum_std.reduce(lambda x,y: x + y)
std = np.sqrt(std/heights.count())'''

test = keyed.map(lambda x: (x[0], x[1][0]))
test = test.reduceByKey(lambda x, y: max(x,y))

test.collect()

Traceback (most recent call last):
  File "/Users/tobiasganzmann/opt/anaconda3/lib/python3.9/site-packages/pyspark/serializers.py", line 458, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
  File "/Users/tobiasganzmann/opt/anaconda3/lib/python3.9/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Users/tobiasganzmann/opt/anaconda3/lib/python3.9/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
  File "/Users/tobiasganzmann/opt/anaconda3/lib/python3.9/site-packages/pyspark/rdd.py", line 356, in __getnewargs__
    raise RuntimeError(
RuntimeError: It appears that you are attempting to broadcast an RDD or reference an RDD from an action or transformation. RDD transformations and actions can only be invoked by the driver, not inside of other transformations; for example, rdd1.map(lambda x: rdd2.values.count() * x) is invalid because the values transformation and count ac

PicklingError: Could not serialize object: RuntimeError: It appears that you are attempting to broadcast an RDD or reference an RDD from an action or transformation. RDD transformations and actions can only be invoked by the driver, not inside of other transformations; for example, rdd1.map(lambda x: rdd2.values.count() * x) is invalid because the values transformation and count action cannot be performed inside of the rdd1.map transformation. For more information, see SPARK-5063.

22/12/13 17:10:02 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 789403 ms exceeds timeout 120000 ms
22/12/13 17:10:02 WARN SparkContext: Killing executors is not supported by current scheduler.


In [5]:
def read_in(filename):
    #read in file and split at ","
    rdd = sc.textFile(filename)
    split_rdd = rdd.map(lambda x : x.split(","))

    #remove unnecessary variables, create primary key (user + model + gt), create floats: counter variable, x, y, z
    keyed = split_rdd.map(lambda x : (x[6] + "," + x[7]+ "," + x[9], np.array([1, float(x[3]), float(x[4]), float(x[5])])))
    return keyed

In [6]:
def calc_mean(rdd):
    # sum up numericals from input rdd --> x[1]: count per key, sum(x), sum(y), sum(z)
    sum = rdd.reduceByKey(lambda x, y : x + y)
    # divide sums by count
    mean = sum.map(lambda x : (x[0], np.array((x[1][1]/x[1][0], x[1][2]/x[1][0], x[1][3]/x[1][0]))))

    return mean


In [7]:
def calc_std(rdd):
    #remove unnecessary variables, create primary key (user + model + gt), create floats: counter variable, x, y, z, x^2, y^2, z^2 
    work_rdd = rdd.map(lambda x : (x[0], np.array([1, x[1][1], x[1][2], x[1][3], (x[1][1])**2, (x[1][2])**2, (x[1][3])**2])))

    # sum up individual numerical values
    sum = work_rdd.reduceByKey(lambda x, y : x + y)
    # calculate std as follows: sqrt( (sum(x^2)/N) - (sum(x)/N)^2 )
    std = sum.map(lambda x : (x[0], np.array([np.sqrt((x[1][4]/x[1][0])-(x[1][1]/x[1][0])**2), np.sqrt((x[1][5]/x[1][0])-(x[1][2]/x[1][0])**2), np.sqrt((x[1][6]/x[1][0])-(x[1][3]/x[1][0])**2)])))

    return std

In [8]:
# def find_max(rdd):
#     rdd = read_in('Watch_gyroscope.csv')
#     rdd = rdd.filter(lambda x : x[0] == 'a,gear,null')
#     first_line = rdd.take(1)
#     count = rdd.count()
#     print(rdd.count())

#     while count > 0:
#         max_x = first_line[0][1][1]
#         maxed_x = rdd.filter(lambda x :  x[1][1] > max_x )
#         count = maxed_x.count()
#         first_line = maxed_x.take(1)
    
#     count = rdd.count()
#     first_line = rdd.take(1)
#     while count > 0:
#         max_y = first_line[0][1][2]
#         maxed_y = rdd.filter(lambda x :  x[1][2] > max_y )
#         count = maxed_y.count()
#         first_line = maxed_y.take(1)
    
#     count = rdd.count()
#     first_line = rdd.take(1)
#     while count > 0:
#         max_z = first_line[0][1][3]
#         maxed_z = rdd.filter(lambda x :  x[1][3] > max_z )
#         count = maxed_z.count()
#         first_line = maxed_z.take(1)

#     return [max_x, max_y, max_z]

In [9]:
def get_keys(rdd):
    
    out = rdd.reduceByKey(lambda x, y: x+y)


    collected = out.collect()
    keys = []
    for i in range(out.count()):
        keys.append(collected[i][0])

    return keys


In [10]:
def find_max(rdd):
    rdd = read_in('Watch_gyroscope.csv')
    keys = get_keys(rdd)
    out = sc.emptyRDD()
    #print(out.collect(), "break\n")

    for i in range(len(keys)):
        key = keys[i]
        #print(key)
        max_values = np.empty([3,1])
        for i in range(3):
            current = rdd.filter(lambda x : x[0]==key)
            #print(current.take(1))
            current_x = current.map(lambda x: (x[0], x[1][i+1]))
            max_x = current_x.max()
            max_values[i] = max_x[1]
            #print(max_x[1])
        
        entry = (str(key), max_values)
        entry_rdd = sc.parallelize([key, max_values])
        #print(entry_rdd.collect())
        out = out.union(entry_rdd)
    #out = out.map(lambda x : (x[0], list(x[1:])))
    #out.collect()
    return out

In [11]:
rdd = read_in('Watch_gyroscope.csv')
keys = get_keys(rdd)
out = sc.emptyRDD()

#def max(rdd):
    
rdd = rdd.map(lambda x: (x[0], x[1][1]))
rdd = rdd.reduceByKey(lambda x, y: max(x,y))
rdd.collect()

IndentationError: expected an indented block (2921980053.py, line 7)

In [ ]:
rdd = read_in('Watch_gyroscope.csv')
keys = get_keys(rdd)
#out = rdd.filter(lambda x : x[0] == 'a,gear,null')
out = find_max(rdd)
print(out.collect())



# for i in range(len(keys)):
#     # print(out.collect()[2*i], out.collect()[2*i+1])
#     out = out.map(lambda x : (x[i]))

out = out.map(lambda x : (x[0][0]))
out.collect()

['a,gear,stand', array([[0.81039995],
       [0.35446674],
       [1.1475562 ]]), 'a,gear,null', array([[ 0.0561927 ],
       [-0.0181095 ],
       [-0.05512743]]), 'a,gear,sit', array([[0.39867523],
       [0.39920786],
       [0.77604514]])]


['a', 0.81039995, 'a', 0.0561927, 'a', 0.39867523]

In [ ]:
rdd = read_in('Watch_gyroscope.csv')
keys = get_keys(rdd)
out = sc.emptyRDD()
#print(out.collect(), "break\n")

for i in range(len(keys)):
    key = keys[i]
    #print(key)
    max_values = np.empty([3,1])
    for i in range(3):
        current = rdd.filter(lambda x : x[0]==key)
        #print(current.take(1))
        current_x = current.map(lambda x: (x[0], x[1][i+1]))
        max_x = current_x.max()
        max_values[i] = max_x[1]
        #print(max_x[1])
    
    entry = (str(key), max_values)
    entry_rdd = sc.parallelize(entry)
    #print(entry_rdd.collect())
    out = out.union(entry_rdd)
#out = out.map(lambda x : (x[0], list(x[1:])))
out.collect()

['a,gear,stand',
 array([[0.81039995],
        [0.35446674],
        [1.1475562 ]]),
 'a,gear,null',
 array([[ 0.0561927 ],
        [-0.0181095 ],
        [-0.05512743]]),
 'a,gear,sit',
 array([[0.39867523],
        [0.39920786],
        [0.77604514]])]

In [ ]:
def find_min(rdd):
    rdd = read_in('Watch_gyroscope.csv')
    keys = get_keys(rdd)
    out = sc.emptyRDD()
    #print(out.collect(), "break\n")

    for i in range(len(keys)):
        key = keys[i]
        #print(key)
        max_values = np.empty([3,1])
        for i in range(3):
            current = rdd.filter(lambda x : x[0]==key)
            #print(current.take(1))
            current_x = current.map(lambda x: (x[0], x[1][i+1]))
            max_x = current_x.min()
            max_values[i] = max_x[1]
            #print(max_x[1])
        
        entry = (str(key), max_values)
        entry_rdd = sc.parallelize(entry)
        #print(entry_rdd.collect())
        out = out.union(entry_rdd)
    #out = out.map(lambda x : (x[0], list(x[1:])))
    #out.collect()
    return out

In [ ]:
def process(filename):
    rdd = read_in(filename)
    mean = calc_mean(rdd)
    std = calc_std(rdd)
    max = find_max(rdd)
    min = find_min(rdd)

    out = mean.union(std)
    out = out.union(max)
    out = out.union(min)
    return (mean + std + max + min)

In [ ]:
out = process('Watch_gyroscope.csv')
out.collect()

[('a,gear,stand', array([ 0.02214666, -0.03286732, -0.07143673])),
 ('a,gear,null', array([ 0.0225701 , -0.03660876, -0.07169494])),
 ('a,gear,sit', array([ 0.02270562, -0.0414225 , -0.0699732 ])),
 ('a,gear,stand', array([0.07314945, 0.05570244, 0.0501775 ])),
 ('a,gear,null', array([0.01779986, 0.01156134, 0.00803968])),
 ('a,gear,sit', array([0.05703369, 0.05626924, 0.04523762])),
 'a,gear,stand',
 array([[0.81039995],
        [0.35446674],
        [1.1475562 ]]),
 'a,gear,null',
 array([[ 0.0561927 ],
        [-0.0181095 ],
        [-0.05512743]]),
 'a,gear,sit',
 array([[0.39867523],
        [0.39920786],
        [0.77604514]]),
 'a,gear,stand',
 array([[-2.0383835 ],
        [-0.55287224],
        [-1.2319783 ]]),
 'a,gear,null',
 array([[-0.0314253 ],
        [-0.08042747],
        [-0.09347696]]),
 'a,gear,sit',
 array([[-0.700944  ],
        [-0.79042625],
        [-0.22849922]])]